# Generated by Django 4.2.5 on 2023-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0002_rename_horairio_final_tiposexames_horario_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoexame',
            name='senha',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
